commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  version_scheme: semver
  version_provider: scm
  update_changelog_on_bump: true
  bump_message: "chore(release): v$new_version"
  version_files:
    - "package.json:version"
